from app.models.schemas import ApiCatalogItem, ToolCatalogItem


from typing import Any


def _default_area_arguments() -> dict[str, Any]:
    # Runtime resolution must come from HA data or explicit entity_id.
    return {}


def _tool_metadata(permission_level: str) -> dict[str, Any]:
    return {
        "tool_version": 1,
        "schema_version": "1.0",
        "permission_level": permission_level,
        "environment_tags": ["home", "prod"],
        "allowed_agents": ["home_automation_agent"],
        "rollout_percentage": 100,
    }


def default_tool_catalog_items() -> list[ToolCatalogItem]:
    return [
        ToolCatalogItem(
            tool_name="home.lights.on",
            domain="auto",
            service="turn_on",
            strategy="light_area",
            description="Turn on lights by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.lights.off",
            domain="auto",
            service="turn_off",
            strategy="light_area",
            description="Turn off lights by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.curtains.open",
            domain="cover",
            service="open_cover",
            strategy="cover_area",
            description="Open curtains by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.curtains.close",
            domain="cover",
            service="close_cover",
            strategy="cover_area",
            description="Close curtains by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.curtains.stop",
            domain="cover",
            service="stop_cover",
            strategy="cover_area",
            description="Stop curtains by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.scene.activate",
            domain="scene",
            service="turn_on",
            strategy="scene_id",
            description="Activate a Home Assistant scene entity",
            default_arguments={},
            **_tool_metadata(permission_level="medium"),
        ),
        ToolCatalogItem(
            tool_name="home.climate.turn_on",
            domain="climate",
            service="turn_on",
            strategy="climate_area",
            description="Turn on climate device by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.climate.turn_off",
            domain="climate",
            service="turn_off",
            strategy="climate_area",
            description="Turn off climate device by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.climate.set_temperature",
            domain="climate",
            service="set_temperature",
            strategy="climate_area_temperature",
            description="Set climate target temperature by area",
            default_arguments=_default_area_arguments(),
            **_tool_metadata(permission_level="medium"),
        ),
        ToolCatalogItem(
            tool_name="home.areas.sync",
            domain="ha",
            service="areas_sync",
            strategy="area_sync",
            description="Ensure target HA areas exist and optionally delete unused areas",
            default_arguments={
                "target_areas": ["玄关", "厨房", "客厅", "主卧", "次卧", "餐厅", "书房", "卫生间", "走廊", "阳台"],
                "delete_unused": True,
                "force_delete_in_use": False,
            },
            **_tool_metadata(permission_level="medium"),
        ),
        ToolCatalogItem(
            tool_name="home.areas.audit",
            domain="ha",
            service="areas_audit",
            strategy="area_audit",
            description="Audit entity area assignment and suggest target area for unassigned entities",
            default_arguments={
                "target_areas": ["玄关", "厨房", "客厅", "主卧", "次卧", "餐厅", "书房", "卫生间", "走廊", "阳台"],
                "domains": ["light", "switch", "climate", "cover", "fan"],
                "include_unavailable": False,
            },
            **_tool_metadata(permission_level="low"),
        ),
        ToolCatalogItem(
            tool_name="home.areas.assign",
            domain="ha",
            service="areas_assign",
            strategy="area_assign",
            description="Assign unassigned entities to HA areas based on audit suggestions",
            default_arguments={
                "target_areas": ["玄关", "厨房", "客厅", "主卧", "次卧", "餐厅", "书房", "卫生间", "走廊", "阳台"],
                "domains": ["light", "switch", "climate", "cover", "fan"],
                "include_unavailable": False,
                "only_with_suggestion": True,
                "max_updates": 200,
            },
            **_tool_metadata(permission_level="medium"),
        ),
    ]


def default_api_catalog_items() -> list[ApiCatalogItem]:
    return [
        ApiCatalogItem(
            endpoint_key="api_catalog",
            display_name="API 管理列表",
            method="GET",
            path="/v1/apis/catalog",
            description="读取 API 管理清单（只读）。",
            sort_order=10,
        ),
        ApiCatalogItem(
            endpoint_key="tool_catalog",
            display_name="工具管理列表",
            method="GET",
            path="/v1/tools/catalog",
            description="读取工具关键字清单（只读展示）。",
            sort_order=20,
        ),
        ApiCatalogItem(
            endpoint_key="tool_whitelist",
            display_name="启用工具关键字",
            method="GET",
            path="/v1/tools/whitelist",
            description="读取可调用工具关键字。",
            sort_order=30,
        ),
        ApiCatalogItem(
            endpoint_key="tool_call",
            display_name="API 调试调用",
            method="POST",
            path="/v1/tools/call",
            description="根据工具关键字调用 HA。",
            request_example={
                "tool_name": "home.lights.on",
                "arguments": {"area": "study"},
                "trace_id": "ui-debug-001",
                "dry_run": False,
            },
            sort_order=40,
        ),
        ApiCatalogItem(
            endpoint_key="device_light_control",
            display_name="设备控制-灯光",
            method="POST",
            path="/v1/device/lights/control",
            description="按 area 或 entity_id 开关灯，适合 Agent 直接调用。",
            request_example={
                "action": "on",
                "area": "study",
                "trace_id": "agent-light-001",
                "dry_run": False,
            },
            sort_order=45,
        ),
        ApiCatalogItem(
            endpoint_key="device_curtain_control",
            display_name="设备控制-窗帘",
            method="POST",
            path="/v1/device/curtains/control",
            description="按 area 或 entity_id 控制窗帘开/关/停。",
            request_example={
                "action": "open",
                "area": "living_room",
                "trace_id": "agent-curtain-001",
                "dry_run": False,
            },
            sort_order=46,
        ),
        ApiCatalogItem(
            endpoint_key="device_climate_control",
            display_name="设备控制-空调",
            method="POST",
            path="/v1/device/climate/control",
            description="空调开关/设温，支持 area 或 entity_id。",
            request_example={
                "action": "set_temperature",
                "area": "bedroom",
                "temperature": 24,
                "trace_id": "agent-climate-001",
                "dry_run": False,
            },
            sort_order=47,
        ),
        ApiCatalogItem(
            endpoint_key="device_custom_control",
            display_name="设备控制-自定义",
            method="POST",
            path="/v1/device/custom/control",
            description="通过工具关键字执行自定义设备能力。",
            request_example={
                "tool_name": "home.scene.activate",
                "arguments": {"scene_id": "scene.movie"},
                "trace_id": "agent-custom-001",
                "dry_run": False,
            },
            sort_order=48,
        ),
        ApiCatalogItem(
            endpoint_key="config_get",
            display_name="读取系统配置",
            method="GET",
            path="/v1/config/ha",
            description="读取当前 HA 运行配置。",
            sort_order=50,
        ),
        ApiCatalogItem(
            endpoint_key="config_put",
            display_name="更新系统配置",
            method="PUT",
            path="/v1/config/ha",
            description="更新 HA 运行配置。",
            request_example={
                "ha_base_url": "http://homeassistant.local:8123",
                "ha_timeout_sec": 6,
                "ha_context_timeout_sec": 8,
            },
            sort_order=60,
        ),
        ApiCatalogItem(
            endpoint_key="context_summary",
            display_name="上下文摘要",
            method="GET",
            path="/v1/context/summary",
            description="返回 Agent 可用上下文。",
            sort_order=70,
        ),
        ApiCatalogItem(
            endpoint_key="ha_overview",
            display_name="HA 总览",
            method="GET",
            path="/v1/ha/overview",
            description="读取 HA 的实体/房间/服务总览统计。",
            sort_order=80,
        ),
        ApiCatalogItem(
            endpoint_key="ha_areas",
            display_name="HA 房间列表",
            method="GET",
            path="/v1/ha/areas",
            description="读取 HA 房间列表（优先 HA 模板能力，回退配置映射）。",
            sort_order=90,
        ),
        ApiCatalogItem(
            endpoint_key="ha_areas_sync",
            display_name="HA 房间同步",
            method="POST",
            path="/v1/ha/areas/sync",
            description="同步目标房间列表，并可删除未使用房间。",
            request_example={
                "target_areas": ["玄关", "厨房", "客厅", "主卧", "次卧", "餐厅", "书房", "卫生间", "走廊", "阳台"],
                "delete_unused": True,
                "force_delete_in_use": False,
                "trace_id": "agent-area-sync-001",
                "dry_run": False,
            },
            sort_order=95,
        ),
        ApiCatalogItem(
            endpoint_key="ha_areas_audit",
            display_name="HA 房间归属审计",
            method="POST",
            path="/v1/ha/areas/audit",
            description="按目标房间审计实体归属，返回未归属实体与建议归属房间。",
            request_example={
                "target_areas": ["玄关", "厨房", "客厅", "主卧", "次卧", "餐厅", "书房", "卫生间", "走廊", "阳台"],
                "domains": ["light", "switch", "climate", "cover", "fan"],
                "include_unavailable": False,
                "trace_id": "agent-area-audit-001",
                "dry_run": False,
            },
            sort_order=96,
        ),
        ApiCatalogItem(
            endpoint_key="ha_areas_assign",
            display_name="HA 房间归属回写",
            method="POST",
            path="/v1/ha/areas/assign",
            description="将未归属实体按建议房间批量回写到 HA 区域。",
            request_example={
                "target_areas": ["玄关", "厨房", "客厅", "主卧", "次卧", "餐厅", "书房", "卫生间", "走廊", "阳台"],
                "domains": ["light", "switch", "climate", "cover", "fan"],
                "include_unavailable": False,
                "only_with_suggestion": True,
                "max_updates": 200,
                "trace_id": "agent-area-assign-001",
                "dry_run": False,
            },
            sort_order=97,
        ),
        ApiCatalogItem(
            endpoint_key="ha_areas_reassign",
            display_name="HA 实体区域重分配",
            method="POST",
            path="/v1/ha/areas/reassign",
            description="按实体ID批量重分配到指定区域（支持 dry_run）。",
            request_example={
                "assignments": [
                    {"entity_id": "switch.ke_ting_can_ting_deng_l1", "area": "客厅"},
                    {"entity_id": "switch.ke_ting_can_ting_deng_l2", "area": "餐厅"},
                ],
                "trace_id": "agent-area-reassign-001",
                "dry_run": False,
            },
            sort_order=98,
        ),
        ApiCatalogItem(
            endpoint_key="ha_entities",
            display_name="HA 实体列表",
            method="GET",
            path="/v1/ha/entities",
            description="读取 HA 全量实体，支持 domain/area/query 过滤。",
            sort_order=100,
        ),
        ApiCatalogItem(
            endpoint_key="ha_entity_state",
            display_name="HA 单实体状态",
            method="GET",
            path="/v1/ha/entities/{entity_id}",
            description="读取指定 entity_id 的状态与属性。",
            sort_order=110,
        ),
        ApiCatalogItem(
            endpoint_key="ha_services",
            display_name="HA 服务列表",
            method="GET",
            path="/v1/ha/services",
            description="读取 HA 可调用服务目录，支持 domain 过滤。",
            sort_order=120,
        ),
        ApiCatalogItem(
            endpoint_key="logs_recent",
            display_name="日志查询",
            method="GET",
            path="/v1/logs/recent",
            description="读取最近操作日志（文件存储，source 支持多选）。",
            sort_order=130,
        ),
        ApiCatalogItem(
            endpoint_key="logs_ui",
            display_name="UI操作日志上报",
            method="POST",
            path="/v1/logs/ui",
            description="UI 上报用户操作日志。",
            request_example={
                "action": "debug.call_api",
                "view": "debug",
                "detail": {"path": "/v1/tools/call"},
                "success": True,
            },
            sort_order=140,
        ),
    ]

